name = "chk"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-04-12"

[placement]
mode = "smart"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "MyDurableObject" ]

[vars]
# Injected Environment Variables for Upstream APIs
UPSTREAM_API1_URL = "https://wallet.payate.com/card/ccn1/alien07.php"
UPSTREAM_API2_URL = "https://mock.payate.com/api.php"
UPSTREAM_TIMEOUT_MS = "5000"
DAILY_CARD_LIMIT = "100"

[[kv_namespaces]]
binding = "KV"
id = "bb8ef261cab04944973a633c28673def"
